matrix:
  include:
    - language: python
      python: 3.6
      env:
        - DB_URI=mongodb://localhost:27017/sfja
      services:
        - mongodb
      before_install:
        - cd api
      install:
        - pip3 install -r requirements.txt
      before_script:
        - sleep 15
        - mongo sfja --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
        - python3 ../bin/resetDatabase.py
      script:
        - python3 tests.py

    - language: node_js
      node_js: node
      before_install:
        - cd sfja
      install:
        - yarn
      script:
        - yarn run lint
